from enum import Enum
import json
from pathlib import Path

from ninja_syntax import Writer

SCRIPTS_DIR = Path(__file__).parent


class BuildType(Enum):
    NORMAL = 1
    DIFFBUILD = 2
    TESTS = 3
    DLLBUILD = 4
    OBJDIFFBUILD = 5


def configure(build_type):
    with (SCRIPTS_DIR.parent / "build.ninja").open("w") as f:
        writer = Writer(f, width=120)
        writer.variable("ninja_required_version", "1.5")

        writer.variable("builddir", "build")

        writer.variable("cl", "cl.exe")
        writer.variable(
            "cl_common_flags",
            "/MT /EHsc /Gs /RTCu /DNDEBUG /Zi /GF /I $builddir/autogenerated /I src /I 3rdparty/munit /I 3rdparty/Detours/src",
        )
        writer.variable("cl_flags", "$cl_common_flags /Oi /Gr")
        writer.variable("cl_flags_pbg", "$cl_common_flags /Od /Oi /Ob0 /Gr")
        writer.variable(
            "cl_flags_detours",
            "/W4 /WX /we4777 /we4800 /Zi /MT /Gy /Gm- /Zl /Od /DDETOUR_DEBUG=0 /DWIN32_LEAN_AND_MEAN /D_WIN32_WINNT=0x501",
        )
        if build_type in [BuildType.DIFFBUILD, BuildType.DLLBUILD]:
            writer.variable("cl_flags", "$cl_flags /DDIFFBUILD")
            writer.variable("cl_flags_pbg", "$cl_flags_pbg /DDIFFBUILD")
        writer.variable("rc", "rc.exe")
        writer.variable("link", "link.exe")
        writer.variable(
            "th08_link_flags",
            "/subsystem:windows /machine:X86 /filealign:512 /incremental:no /opt:icf /opt:ref /map /mapinfo:exports /mapinfo:lines",
        )

        writer.variable("msvc_deps_prefix", "Note: including file:")
        writer.rule(
            "cc",
            "$cl /nologo /showIncludes $cl_flags /c $in /Fd$out.pdb /Fo$out",
            deps="msvc",
        )
        writer.rule(
            "cc_pbg",
            "$cl /nologo /showIncludes $cl_flags_pbg /c $in /Fd$out.pdb /Fo$out",
            deps="msvc",
        )
        writer.rule(
            "cc_detours",
            "$cl /nologo /showIncludes $cl_flags_detours /Fd$out.pdb /Fo$out /c $in",
            deps="msvc",
        )
        writer.rule("genglobals", "python scripts/generate_globals.py $in $out")
        writer.rule("rc", "$rc /fo $out $in")
        writer.rule(
            "link",
            "$link $link_flags /nologo /out:$out $link_libs $in",
        )
        writer.rule(
            "copyicon",
            'python -c "import shutil; import sys; shutil.copyfile(sys.argv[1], sys.argv[2])" $in $out',
        )
        writer.rule(
            "geni18n",
            "python scripts/generate_i18n.py -o $out --shift-jis $in",
        )
        writer.rule(
            "gendetours",
            "python scripts/generate_detours.py --input-def $builddir/th08.def --output $out",
        )
        writer.rule(
            "gendef",
            "python scripts/gendef.py --output $out $in",
        )
        writer.rule(
            "rename_symbols",
            "python scripts/generate_objdiff_objs.py $in",
        )

        cxx_flags_per_source = {
            "AsciiManager": "/Od",
            "Background": "/Od",
            "Ending": "/Od",
            "EnemyManager": "/Od",
            "GameManager": "/Os",
            "utils": "/Od",
            "Global": "/Od",
            "TextHelper": "/Os",
            "main": "/Od",
            "Midi": "/Od",
            "Supervisor": "/Os /Ob1",
            "MusicRoom": "/Od",
            "ReplayManager": "/Od",
            "ResultScreen": "/Os",
            "ScoreDat": "/Od",
            "ScreenEffect": "/Od",
            "SoundPlayer": "/Od",
            "AnmManager": "/Od",
            "Title": "/Od",
            "zwave": "/Od",
        }

        for key, value in cxx_flags_per_source.items():
            writer.rule(
                "cc_" + key,
                "$cl /nologo /showIncludes $cl_flags "
                + value
                + " /c $in /Fd$out.pdb /Fo$out",
                deps="msvc",
            )

        cxx_sources = [
            "AsciiManager",
            "Background",
            "Ending",
            "EnemyManager",
            "GameManager",
            "utils",
            "Global",
            "TextHelper",   # grpfont.obj
            "main",
            "Midi",
            "Supervisor",   # mother.obj
            "MusicRoom",
            "ReplayManager",
            "ResultScreen",
            "ScoreDat",
            "ScreenEffect",
            "SoundPlayer",
            "AnmManager",   # sprtlib.obj
            "Title",
            "zwave",
        ]

        pbg_sources = [
            "PbgFile",
            "Lzss",
            "PbgArchive",
        ]

        munit_sources = ["munit"]

        test_sources = []

        detours_sources = [
            "detours",
            "modules",
            "disasm",
            "image",
            "creatwth",
            "disolx86",
            "disolx64",
            "disolia64",
            "disolarm",
            "disolarm64",
        ]

        # TODO: might make more sense to work the other way around: generate
        # objdiff.json from the ninja.
        with open("objdiff.json") as f:
            objdiff_json = json.load(f)
        objdiff_deps = []
        for obj in objdiff_json.get("objects", {}):
            objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
        for obj in objdiff_json.get("units", {}):
            objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
        writer.build("objdiff", "phony", [], objdiff_deps)

        for rule in cxx_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_" + rule,
                "src/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )
            writer.build(
                "$builddir/objdiff/reimpl/" + rule + ".obj",
                "rename_symbols",
                "$builddir/" + rule + ".obj",
                implicit=["scripts/generate_objdiff_objs.py"],
            )

        for rule in pbg_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_pbg",
                "src/pbg/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )
            writer.build(
                "$builddir/objdiff/reimpl/" + rule + ".obj",
                "rename_symbols",
                "$builddir/" + rule + ".obj",
                implicit=["scripts/generate_objdiff_objs.py"],
            )

        for rule in munit_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "3rdparty/munit/" + rule + ".c",
            )

        for rule in test_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "tests/" + rule + ".cpp",
            )

        for rule in detours_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_detours",
                "3rdparty/Detours/src/" + rule + ".cpp",
            )

        writer.build(
            "$builddir/autogenerated/detouring.cpp",
            "gendetours",
            implicit=[
                "config/implemented.csv",
                "config/mapping.csv",
                "scripts/generate_detours.py",
                "$builddir/th08.def",
            ],
        )
        writer.build(
            "$builddir/dllbuild.obj",
            "cc",
            "src/dllbuild.cpp",
            implicit=[
                "$builddir/autogenerated/detouring.cpp",
                "$builddir/autogenerated/i18n.hpp",
            ],
        )

        writer.build(
            "$builddir/globals.obj",
            "genglobals",
            inputs="config/globals.csv",
            implicit=["scripts/generate_globals.py"],
        )
        writer.build("$builddir/autogenerated/i18n.hpp", "geni18n", "config/i18n.csv")
        writer.build("$builddir/icon.ico", "copyicon", "resources/placeholder.ico")
        writer.build(
            "$builddir/th08.res",
            "rc",
            inputs="resources/th08.rc",
            implicit="$builddir/icon.ico",
        )
        writer.build(
            "$builddir/th08.def",
            "gendef",
            inputs=[
                "$builddir/" + x + ".obj"
                for x in (cxx_sources + pbg_sources)
            ],
            implicit=["scripts/gendef.py"],
        )
        objfiles = (
            ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in pbg_sources]
            + ["$builddir/th08.res"]
        )
        if build_type in [BuildType.DIFFBUILD, BuildType.DLLBUILD]:
            objfiles += ["$builddir/globals.obj"]

        th08_link_libs = "dxguid.lib d3dx8.lib d3d8.lib dsound.lib winmm.lib kernel32.lib user32.lib dinput8.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib"
        writer.build(
            "$builddir/th08.exe",
            "link",
            inputs=objfiles,
            variables={
                "link_libs": th08_link_libs,
                "link_flags": "$th08_link_flags /debug /pdb:$builddir/th08.pdb",
            },
        )

        test_objfiles = (
            ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in pbg_sources]
            + ["$builddir/" + src + ".obj" for src in test_sources]
        )
        writer.build(
            "$builddir/th08e-tests.exe",
            "link",
            inputs=test_objfiles + ["$builddir/munit.lib"],
            variables={
                "link_libs": th08_link_libs + " $builddir/munit.lib",
                "link_flags": "/debug /pdb:$builddir/th08e.pdb",
            },
        )

        writer.build(
            "$builddir/th08e.dll",
            "link",
            inputs=objfiles + ["$builddir/dllbuild.obj", "$builddir/detours.lib"],
            implicit=["$builddir/th08.def"],
            variables={
                "link_libs": th08_link_libs,
                "link_flags": "/DLL /debug /pdb:$builddir/th08e.pdb /export:DetourFinishHelperProcess,@1,NONAME /def:$builddir/th08.def /export:Direct3DCreate8 /export:malloc /export:calloc /export:realloc /export:??2@YAPAXI@Z /export:free /export:_msize",
            },
        )

        writer.build(
            "$builddir/munit.lib",
            "link",
            inputs=["$builddir/" + s + ".obj" for s in munit_sources],
            variables={"link_flags": "/lib", "link_libs": ""},
        )

        writer.build(
            "$builddir/detours.lib",
            "link",
            inputs=["$builddir/" + s + ".obj" for s in detours_sources],
            variables={"link_flags": "/lib"},
        )

        writer.close()


if __name__ == "__main__":
    configure(BuildType.NORMAL)
